[package]
name = "ADGWebsite"
version = "1.0.0"
authors = ["Ashlin Darius Govindasamy"]
edition = "2021"

[dependencies]
actix-web = "3"
actix-files = "0.3"
actix-session = "0.4"
actix-utils = "2"
env_logger = "0.8"
